-- MySQL Script generated by MySQL Workbench
-- Sat Apr  8 23:16:23 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MyJoinsDB
-- -----------------------------------------------------
-- MySQL Essential. 4. JOIN-s

-- -----------------------------------------------------
-- Schema MyJoinsDB
--
-- MySQL Essential. 4. JOIN-s
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MyJoinsDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `MyJoinsDB` ;

-- -----------------------------------------------------
-- Table `MyJoinsDB`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyJoinsDB`.`Person` (
  `personId` INT NOT NULL auto_increment,
  `fullName` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(12) NULL,
  PRIMARY KEY (`personId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MyJoinsDB`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyJoinsDB`.`Employee` (
  `personId` INT NOT NULL,
  `Salary` DECIMAL(12,2) NULL,
  `position` VARCHAR(45) NULL,
  INDEX `Employee_fk1_idx` (`personId` ASC) VISIBLE,
  CONSTRAINT `Employee_fk1`
    FOREIGN KEY (`personId`)
    REFERENCES `MyJoinsDB`.`Person` (`personId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MyJoinsDB`.`Contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyJoinsDB`.`Contact` (
  `personId` INT NOT NULL,
  `birthDate` DATE NULL,
  `address` VARCHAR(45) NULL,
  `family` VARCHAR(45) NULL,
  INDEX `contact_fk1_idx` (`personId` ASC) VISIBLE,
  CONSTRAINT `contact_fk1`
    FOREIGN KEY (`personId`)
    REFERENCES `MyJoinsDB`.`Person` (`personId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
